name: Generate Jacoco Badge

on:
  push:
    branches: [ main ]   # ✅ only run on main
  pull_request:
    branches: [ main ]

jobs:
  jacoco-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests with coverage
        run: ./gradlew clean test jacocoTestReport

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-coverage-badge: true
          jacoco-csv-file: app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.csv
          badges-directory: .github/badges

      - name: Upload badge as artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-badge
          path: .github/badges/jacoco.svg

      - name: Commit badge to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update JaCoCo coverage badge"
          file_pattern: .github/badges/jacoco.svg
